//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TitlesForCasinos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Downloads\\")]
        public string ScreenshotsDir {
            get {
                return ((string)(this["ScreenshotsDir"]));
            }
            set {
                this["ScreenshotsDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Dev\\MySiteParser\\MySiteParser\\MySiteParser\\WorkingDir\\CasinoSitesTitles\\")]
        public string DataDir {
            get {
                return ((string)(this["DataDir"]));
            }
            set {
                this["DataDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int CurrentId {
            get {
                return ((int)(this["CurrentId"]));
            }
            set {
                this["CurrentId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Dev\\MySiteParser\\MySiteParser\\MySiteParser\\WorkingDir\\CasinoSitesTitles\\")]
        public string WorkingDir {
            get {
                return ((string)(this["WorkingDir"]));
            }
            set {
                this["WorkingDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\rudak\\AppData\\Local\\Mozilla Firefox\\firefox.exe")]
        public string BrowserPath {
            get {
                return ((string)(this["BrowserPath"]));
            }
            set {
                this["BrowserPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Dev\\MySiteParser\\MySiteParser\\MySiteParser\\WorkingDir\\CasinoSitesTitles\\Casino" +
            "SitesTitles.litedb")]
        public string DBPath {
            get {
                return ((string)(this["DBPath"]));
            }
            set {
                this["DBPath"] = value;
            }
        }
    }
}
